{% set name = "mljar-scikit-plot" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9a6a6c6fdfa277a0ced22872350336556d3c8022f3618ad0c7c0ed236069746

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=1.4.0
    - scikit-learn >=1.1.0
    - scipy >=1.11.4
    - joblib >=0.10

test:
  imports:
    - scikitplot
  commands:
    - pip check
  requires:
    - pip
    
about:
  home: https://github.com/mljar/mljar-scikit-plot
  summary: An intuitive library to add plotting functionality to scikit-learn object
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pplonski
